### ISSUE TITLE
Python 3 and QT5

### ISSUE THREAD

**Issue by jdha** [NOC-MSM/PyNEMO#23]
At the moment pynemo relies on QT4 - we could keep using the environment.yml to stick with old packages... but if we move to python3 then we probably need to get things working using QT5

**Comment by jpolton** [comment]
Email exchange with NOC-IT in Nov'19:

TomE,
 
We need to make the transition from python 2 to 3. I am pleased to hear it won’t be forced on us when we have issues enough with ARCHER coming offline in Feb.
I am surprised that you only see BODC activity related to python 2, perhaps we are invoking python 2 via conda or something?
Turning off python 2 would break our PyNEMO code that supports several projects (NOWMAPS, SANH, ACCORD, IMMERSE).
I cc TomP, who is developing PyNEMO – Tom, perhaps we need to make the notes about the update to Python3 an To-do Action?
 
Jeff
 
From: NOC - Servicedesk <servicedesk@noc.ac.uk>
Date: Thursday, 21 November 2019 at 12:16
To: "Polton, Jeffrey" <jelt@noc.ac.uk>
Subject: INC-2424 - python 2 end of life
 
Hi Jeff,
 
It will still be supported by Red Hat ( CentOS) within the OS.
We need to consider removing python 2 from software modules. 
From modules logs I can only bodc using python 2.7.5 over the past 30 days.
 
Could you let me know of any impact caused by removing the 3 version 2 modules.
Thanks
Tom

**Comment by jdha** [comment]
My idea had been to wait until the code was in a fit state to release (with tides too) and then run 2to3 on it and go from there. The biggest issue I can see is moving to QT5 and whether pyjnius will provide the same functionality at v3.

**Comment by jdha** [comment]
As this issue has been escalated with the imminent removal of Py2 from the NOCL systems I've gone ahead a forked PyNEMO with the aim of moving it to Py3. The master code is not yet in a alpha state... but that will have to wait until post 2to3.
